### ISSUE TITLE
typo in terminal tricks

### ISSUE THREAD

**Issue by caustee** [onceupon/Bash-Oneliner#2]
Hi,

First thing I just want to congratulate you on this great list. I was looking for something like this for a while and I'm glad to see that you did a fantastic job compiling this list.
Now I just want to let you know about a typo I've noticed Terminal Tricks / Change case: https://github.com/onceupon/Bash-Oneliner#change-case
`Esc + l` changes the text to lowercase not uppercase.

**Comment by onceupon** [comment]
Thank you for letting me know, i have fixed it, thanks!
