### ISSUE TITLE
In "data wrangling", one correction and a new suggestion

### ISSUE THREAD

**Issue by fizbin** [onceupon/Bash-Oneliner#31]
First off, at the beginning of the "data wrangling" section, in the example output for the `look` command, you say that you are running the command `look phy|head -n 10` but the output does not show words beginning with `phy`. It instead shows word beginning with `Phi`. I would change this section to:

    ##### Print some words that start with a particular string (e.g. words start with 'phy')
    ```bash
    # If file is not specified, the file /usr/share/dict/words is used.
    look phy|head -n 10
    # Phyciodes
    # phycite
    # Phycitidae
    # phycitol
    # phycochromaceae
    # phycochromaceous
    # phycochrome
    # Phycochromophyceae
    # phycochromophyceous
    # phycocyanin
    ```

Secondly, I would add some usage of the command `comm` to find between two sorted files common lines, lines in one file but not in another; something like:

    ##### Find common/differing lines
    The command `comm` can be used to find lines common to two files (intersection), or to find lines in one file and not in another file. **Warning**: input files must be sorted.
    ```bash
    # Sort input before handing to comm; the -o option lets you sort a file in-place
    sort -o bad-actors.txt bad-actors.txt
    sort -o invited-guests.txt invited-guests.txt
    # Find lines in both files
    comm -12 bad-actors.txt invited-guests.txt
    # Find lines in invited-guests.txt that are NOT in bad-actors.txt
    comm -13 bad-actors.txt invited-guests.txt
    # Find lines that are in good-actors.txt but NOT in invited-guests.txt.
    # Note that since we didn't sort good-actors.txt above, we need to sort it before handing it to comm
    comm -23 <(sort good-actors.txt) invited-guests.txt
    ```

This can also be combined with use of `jq` to do things like "compare these two json arrays of strings, and find the strings that are in both arrays".

**Comment by onceupon** [comment]
fixed example output for `look phy|head -n 10` in commit [ab2ecc0](https://github.com/onceupon/Bash-Oneliner/commit/ab2ecc058d902c90ccf81c15ae823fccd769356c)

**Comment by onceupon** [comment]
will further test and include `comm`, thanks for the cool command

**Comment by onceupon** [comment]
`comm` examples added in [bca6221](https://github.com/onceupon/Bash-Oneliner/commit/bca6221ed3c0a67c0632f302978ec71cc1f9fa86), thanks for the command!
