### ISSUE TITLE
pgrep is not grep -P

### ISSUE THREAD

**Issue by planet36** [onceupon/Bash-Oneliner#40]
The program `pgrep` is not `grep -P`.
`pgrep` was removed from the grep repo in 2000. [0]

[0] https://git.savannah.gnu.org/cgit/grep.git/tree/ChangeLog-2009#n2069

**Comment by onceupon** [comment]
fixed in [6576e5a](https://github.com/onceupon/Bash-Oneliner/commit/6576e5a685670b35b4d40ce8ac2a73cfae8a9a1a).
pgrep is a command for looking up processes, thank you for the correction.
