### ISSUE TITLE
Bash-Oneliner as an Jupyter Notebook tree

### ISSUE THREAD

**Issue by binlab** [onceupon/Bash-Oneliner#47]
Nice collection of examples! Thank you for your work!

Did you consider the conversion of **Bash-Oneliner** to **Jupyter Notebook** tree as an option? 
This can provide more interactivity and structuralism for examples

**Comment by onceupon** [comment]
thank you for the suggestion! I love jupyter and it's great for user to test and interact with all the oneliner commands. However, not all commands here can fit into one notebook, and a lot more examples (files/directories/variables) would have to be well prepared in the notebook for all the commands to run. The complexity is high when converting the entire markdown to a notebook, it might be better to start a new project and select some commands for the notebook, I would definitely love to do this some day.
